#!/usr/bin/env node
// Wraps CoProducer.maxpat into CoProducer.amxd so the device can be built
// without opening Max and doing File > Save As by hand.
//
// The .amxd container is three length-prefixed chunks, confirmed byte for byte
// against the stock templates that ship with Live 12 Suite
// (Contents/App-Resources/Misc/Max Devices/*.amxd):
//
//   "ampf" + uint32le(4) + "mmmm"
//   "meta" + uint32le(4) + uint32le(0)
//   "ptch" + uint32le(len) + <patcher JSON bytes> + 0x00
//
// The ptch length counts the trailing NUL. Run:  node device/build-amxd.js

const fs = require('fs');
const path = require('path');

const dir = __dirname;
const src = path.join(dir, 'CoProducer.maxpat');
const out = path.join(dir, 'CoProducer.amxd');

const raw = fs.readFileSync(src, 'utf8');

// Parse before writing. A patcher that is not valid JSON produces an .amxd that
// Live opens as an empty device with no error worth reading.
let patcher;
try {
  patcher = JSON.parse(raw);
} catch (e) {
  console.error('CoProducer.maxpat is not valid JSON: ' + e.message);
  process.exit(1);
}

// Walk every box in the device, descending into subpatchers. The UI lives in a
// "p coproducer-ui" subpatcher so it can open as its own window, so anything
// that rewrites or inspects boxes has to recurse or it will silently skip it.
function eachBox(p, fn) {
  for (const b of p.boxes || []) {
    if (!b.box) continue;
    fn(b.box);
    if (b.box.patcher) eachBox(b.box.patcher, fn);
  }
}

// Live decides the device type from the I/O objects in the patcher, not from
// anything in the header, so check them here rather than discovering it by
// dragging the device onto the wrong kind of track. Only the top level counts,
// midiin inside a subpatcher does not make the device a MIDI effect.
const texts = (patcher.patcher.boxes || [])
  .map((b) => (b.box && b.box.text) || '')
  .map((t) => t.split(/\s+/)[0]);
const has = (name) => texts.includes(name);

// The device type is carried twice, once as the ampf chunk payload and once as
// project.amxdtype (the same four characters read as a big endian uint32). Both
// come from the stock templates: mmmm MIDI effect, aaaa audio effect, iiii
// instrument.
let kind = null;
let tag = null;
if (has('midiin') && has('midiout')) { kind = 'MIDI effect'; tag = 'mmmm'; }
else if (has('plugin~') && has('plugout~')) { kind = 'audio effect'; tag = 'aaaa'; }
else if (has('midiin') && has('plugout~')) { kind = 'instrument'; tag = 'iiii'; }

if (!kind) {
  console.error(
    'No recognizable Live I/O objects found. A MIDI effect needs midiin and ' +
      'midiout, an audio effect needs plugin~ and plugout~, an instrument ' +
      'needs midiin and plugout~.'
  );
  process.exit(1);
}

// Every .amxd Max writes carries a project block, and devpath "." is what makes
// Max treat the device's own folder as its search root. Without it the device
// still loads, but adjacent files do not resolve and Live logs
// "js: can't find file lom-bridge.js" with node.script silently failing too.
// The .maxpat is kept free of this so it stays readable, it is injected here.
if (!patcher.patcher.project) {
  patcher.patcher.project = {
    version: 1,
    creationdate: 3590052786,
    modificationdate: 3590052786,
    viewrect: [0, 0, 300, 500],
    autoorganize: 1,
    hideprojectwindow: 1,
    showdependencies: 1,
    autolocalize: 0,
    contents: { patchers: {} },
    layout: {},
    searchpath: {},
    detailsvisible: 0,
    amxdtype: Buffer.from(tag, 'ascii').readUInt32BE(0),
    readonly: 0,
    devpathtype: 0,
    devpath: '.',
    sortmode: 0,
    viewmode: 0,
  };
}

// Max does not reliably search the device's own folder for a hand built .amxd,
// confirmed from Max's own log: "can't find file lom-bridge.js" even with the
// device and the script sitting in the same directory. Rather than fight the
// search path, the two file references are rewritten to absolute paths here.
// The .maxpat keeps its portable relative paths, the built .amxd is a machine
// specific artifact anyway (and is regenerated by running this script).
const abs = {
  'lom-bridge.js': path.join(dir, 'lom-bridge.js'),
  '../node/main.js': path.resolve(dir, '..', 'node', 'main.js'),
};
for (const [rel, full] of Object.entries(abs)) {
  if (!fs.existsSync(full)) {
    console.error('missing dependency: ' + full);
    process.exit(1);
  }
  if (/\s/.test(full)) {
    console.error('path contains a space, Max would split it into arguments: ' + full);
    process.exit(1);
  }
}

let rewrote = 0;
eachBox(patcher.patcher, (box) => {
  if (typeof box.text !== 'string' || box.maxclass !== 'newobj') return;
  for (const [rel, full] of Object.entries(abs)) {
    // Match the reference as a whole argument so a comment mentioning the same
    // filename is left alone.
    const parts = box.text.split(/\s+/);
    const at = parts.indexOf(rel);
    if (at > 0) {
      parts[at] = full;
      box.text = parts.join(' ');
      rewrote++;
    }
  }
});

if (rewrote !== Object.keys(abs).length) {
  console.error(
    'expected to rewrite ' + Object.keys(abs).length + ' file references, ' +
      'rewrote ' + rewrote + '. The patcher objects may have changed.'
  );
  process.exit(1);
}

// The jweb UI is pointed at by a message box, not an object box. It is NOT
// loaded from file://: Vite emits <script type="module">, and Chromium refuses
// to load ES modules over file:// because the origin is null, so the bundle
// never boots and jweb shows "site can't be reached". node/main.js serves the
// same files over HTTP on the socket port, so jweb gets a real origin.
const uiIndex = path.resolve(dir, '..', 'ui', 'dist', 'index.html');
if (!fs.existsSync(uiIndex)) {
  console.error(
    'missing ' + uiIndex + '. Build the UI first: cd ui && npm install && npm run build'
  );
  process.exit(1);
}

// Keep this in step with COPRODUCER_WS_PORT in .env and DEFAULT_PORT in main.js.
const uiPort = process.env.COPRODUCER_WS_PORT || '7400';
const uiUrl = 'http://127.0.0.1:' + uiPort + '/index.html';

let uiRewrote = 0;
eachBox(patcher.patcher, (box) => {
  if (box.maxclass !== 'message') return;
  if (/^url\s+/.test(box.text || '')) {
    box.text = 'url ' + uiUrl;
    uiRewrote++;
  }
});

if (uiRewrote !== 1) {
  console.error('expected exactly one jweb url message box, found ' + uiRewrote);
  process.exit(1);
}

function chunk(id, data) {
  const head = Buffer.alloc(8);
  head.write(id, 0, 4, 'ascii');
  head.writeUInt32LE(data.length, 4);
  return Buffer.concat([head, data]);
}

const json = Buffer.from(JSON.stringify(patcher, null, '\t'), 'utf8');
const ptch = Buffer.concat([json, Buffer.from([0])]);

const amxd = Buffer.concat([
  chunk('ampf', Buffer.from(tag, 'ascii')),
  chunk('meta', Buffer.alloc(4)),
  chunk('ptch', ptch),
]);

fs.writeFileSync(out, amxd);

console.log('wrote ' + path.relative(process.cwd(), out));
console.log('  device type: ' + kind);
console.log('  size: ' + amxd.length + ' bytes');
